### ISSUE TITLE
Déploiement nouvelle version

### ISSUE THREAD

**Issue by cbna-api** [cbna-api/cbna-webapps#35]
Est-ce que tout fonctionne bien ?

**Comment by cbna-api** [comment]
Chevobbe Nicolas ( n.chevobbe@atolcd.com ) : Test commentaire

**Comment by gildeluermoz** [comment]
Impossible d'ajouter une nouvelle ZP dans bilan stationnel

**Comment by nchevobbe** [comment]
Cela devrait être corrigé maintenant. Désolé pour ce bug

**Comment by gildeluermoz** [comment]
Effectivement ça fonctionne de nouveau. Merci Nicolas pour ta réactivité.

**Comment by paulsegura** [comment]
au moins on voit que ça fonctionne...
