### ISSUE TITLE
Problème export ZP

### ISSUE THREAD

**Issue by cbna-api** [cbna-api/cbna-webapps#37]
Dans l'appli Bilan stationnel
Lors de l'export en shape, le fichier censé contenir les ZP est vide (les AP, quant à elles, sont bien exportées).
Test réalisé sur Orchis coriophora et Matthiola valesiaca.
L'export fonctionne pour le Liparis (via l'appli Bilan stationnel).

**Comment by paulsegura** [comment]
je vérifie ça tout de suite et je vois si je peux réparer

**Comment by paulsegura** [comment]
Effectivement, j'ai refais les même test que toi à l'export, et j'ai eu le même résultat...
Je signale donc ça à Nicolas, mais tu n'auras la réponse que la semaine prochaine

**Comment by cbna-api** [comment]
Segura Paul ( p.segura@cbn-alpin.fr ) : bonjour
le problème est résolu
tu peux refaire tes exports
n'hésite pas à me signaler les bugs que tu pourrais rencontrer
