### ISSUE TITLE
Données serratule

### ISSUE THREAD

**Issue by cbna-api** [cbna-api/cbna-webapps#39]
Je n'arrive pas à enregistrer des transects sur des fiches !!! Faut-il les dessiner d'abord sur l'AP pour pouvoir les enregistrer ensuite car si c'est le cas n'ayant pas les pointages GPS je ne peux pas !!!

**Comment by paulsegura** [comment]
effectivement il faut d'abord les tracer pour ouvrir la boîte de dialogue "transects"

**Comment by paulsegura** [comment]
j'ai vu avec Noémie
donc je note : possibilité de renseigner un transect sans le tracer

**Comment by paulsegura** [comment]
fera l'objet d'une évolution future, car pas demandé en dec 2015
