### ISSUE TITLE
Problème rencontré

### ISSUE THREAD

**Issue by cbna-api** [cbna-api/cbna-webapps#41]
Il arrive que lorsque j'essaye d'ouvrir certaines fiches un petit message m'indique "un problème a été rencontré"

**Comment by paulsegura** [comment]
regarde si les champs obligatoires (en rouge) sont bien remplis
ou si "étape3-transect" > "méthode" = "Nouveau transect" et que tu n'as pas fait de transect.. dans ce cas il faut mettre "estimation"
