### ISSUE TITLE
Problème de connexion au serveur

### ISSUE THREAD

**Issue by cbna-api** [cbna-api/cbna-webapps#42]
Pour la grosse zone indexAP 950266 pour laquelle il y a eu des transects dupliqués à l'infini lorsque je veux effectuer une modif dessus un petit message m'indique "problème de connexion au serveur" et je ne peux donc pas enregistrer mes modifs

**Comment by paulsegura** [comment]
ça vient peut-être de notre faible connexion web, en plus je fais des transferts sur le site web et Stéphanie est en vidéo-conférence en haut
