### ISSUE TITLE
Repositionnement des transects

### ISSUE THREAD

**Issue by cbna-api** [cbna-api/cbna-webapps#44]
Il est des fois très difficile de modifier un transect lorsqu’il a été créé ex ZP 3076 je n'ai pas réussi à modifier un transect

**Comment by paulsegura** [comment]
c'est un transect que tu as créé toi même ou un "vieux"?
ou ne serait-ce pas encore à cause de la lenteur de notre connexion? le temps de réaction peut-être très long entre le clique et son résultat
