### ISSUE TITLE
Ajout observateurs

### ISSUE THREAD

**Issue by cbna-api** [cbna-api/cbna-webapps#57]
Re-bonjour,
mon précédent ticket est parti trop vite ...il faudrait donc me rajouter les observateurs suivants pour que je puisse faire ma saisie :
 Emilie BERNARD
Christelle Dubosson
Alexandre Guillemot
Laurence Marchionini

Merci

Dominique Cen 74

**Comment by paulsegura** [comment]
Je les ai ajoutés aux observateurs, organisme cen 74
